/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CentrosRouteImport } from './routes/centros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentroSlugRouteImport } from './routes/centro.$slug'

const CentrosRoute = CentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroSlugRoute = CentroSlugRouteImport.update({
  id: '/centro/$slug',
  path: '/centro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/centro/$slug': typeof CentroSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/centro/$slug': typeof CentroSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centros': typeof CentrosRoute
  '/centro/$slug': typeof CentroSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/centros' | '/centro/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/centros' | '/centro/$slug'
  id: '__root__' | '/' | '/centros' | '/centro/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentrosRoute: typeof CentrosRoute
  CentroSlugRoute: typeof CentroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/centros': {
      id: '/centros'
      path: '/centros'
      fullPath: '/centros'
      preLoaderRoute: typeof CentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro/$slug': {
      id: '/centro/$slug'
      path: '/centro/$slug'
      fullPath: '/centro/$slug'
      preLoaderRoute: typeof CentroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentrosRoute: CentrosRoute,
  CentroSlugRoute: CentroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
